@IntegrationTestsDemo.Api_HostAddress = http://localhost:5233/api


GET {{IntegrationTestsDemo.Api_HostAddress}}/customers
Accept: application/json

###

GET {{IntegrationTestsDemo.Api_HostAddress}}/customers/1
Accept: application/json

###

POST {{IntegrationTestsDemo.Api_HostAddress}}/customers
Content-Type: application/json

{
  "firstName": "Pancho",
  "lastName": "Geshov"
}